# Generated by Django 4.1.1 on 2022-09-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_api', '0002_product_description_product_name_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.PositiveIntegerField(default=0, help_text='Rating for this product'),
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('join_date', models.DateField()),
                ('rating', models.PositiveIntegerField(default=0, help_text='Rating for seller')),
                ('product', models.ManyToManyField(to='products_api.product')),
            ],
        ),
    ]
