# Generated by Django 4.1.1 on 2022-09-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_api', '0005_delete_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imageUrl',
            field=models.URLField(default=''),
        ),
    ]
