# Generated by Django 4.1.1 on 2022-09-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_api', '0006_product_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.CharField(max_length=100),
        ),
    ]
