# Generated by Django 4.1.1 on 2022-09-26 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers_api', '0002_remove_seller_address_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='town',
            new_name='city',
        ),
    ]
