# Generated by Django 4.1.1 on 2022-09-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers_api', '0003_rename_town_address_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='seller',
        ),
        migrations.AddField(
            model_name='seller',
            name='address',
            field=models.ManyToManyField(to='sellers_api.address'),
        ),
    ]
