# Generated by Django 4.1.1 on 2022-09-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers_api', '0004_remove_address_seller_seller_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='logoUrl',
            field=models.URLField(default=''),
        ),
    ]
