# Generated by Django 4.1.1 on 2022-09-30 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers_api', '0008_alter_address_latitude_alter_address_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='logoUrl',
        ),
    ]
