# Generated by Django 4.1.1 on 2022-10-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers_api', '0009_remove_seller_logourl'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(default=models.CharField(max_length=100), max_length=100),
        ),
    ]
