# Generated by Django 4.1.1 on 2022-10-01 15:40

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sellers_api', '0010_address_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(default=django.db.models.fields.CharField.db_parameters, max_length=100),
        ),
    ]
